[package]
name = "ml_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ort = "2.0.0-rc.7"
ndarray = "0.16"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
image = "0.25.5"
nalgebra = "0.33.2"
rayon = "1.10.0"
